#!/bin/bash
# ~/repos/scripts/nas/install-git-nas.sh
# 2026-08-07
#
# Installs a real, native git on FleetNAS WITHOUT touching the appliance OS:
# no apt, no root, no Docker, nothing written outside $HOME.
#
# Why this works: FleetNAS is genuine Debian 12 (bookworm), and every one of
# git's runtime deps (libc6, libcurl3-gnutls, libexpat1, libpcre2-8-0, zlib1g)
# plus perl/less/ssh is already present on the host. So the stock Debian
# bookworm git binary runs natively — it just needs unpacking somewhere and
# pointing at its own helper directory.
#
# Why not the alternatives:
#   apt install git  - works, but mutates the appliance's package state and is
#                      wiped by UGREEN firmware updates.
#   Docker           - dhm is not in the docker group, so every call would be
#                      `sudo docker ...`, and the container runs as root, which
#                      is what left root-owned 777 files all over ~/repos.
#
# $HOME is on the btrfs data volume (the RAID array), so this install survives
# an OS reinstall. To undo it: rm -rf ~/git ~/bin/git, drop the PATH block
# from ~/.bashrc.
#
# Run ON FleetNAS, as dhm:   ./install-git-nas.sh
# Re-running is safe (idempotent).

set -u

# Pinned to the bookworm build. NOT the newest git in the pool — that one is
# built against a later glibc and dies with "GLIBC_2.38 not found" here.
# To bump: find the current bookworm/bookworm-security version and its SHA256 in
#   https://deb.debian.org/debian/dists/bookworm/main/binary-amd64/Packages.gz
GIT_VER="1:2.39.5-0+deb12u3"
GIT_DEB="git_2.39.5-0+deb12u3_amd64.deb"
GIT_URL="https://deb.debian.org/debian/pool/main/g/git/${GIT_DEB}"
GIT_SHA="637a85ddd6247fab13bdd0592f2f39aff04ce4dbf0655d3ab553ac359a38ce6f"

PREFIX="${HOME}/git"
BINDIR="${HOME}/bin"
DLDIR="${HOME}/.cache/git-install"

say() { printf '  %s\n' "$*"; }

echo "=========================================="
echo "   INSTALL NATIVE GIT ON FLEETNAS         "
echo "=========================================="

# --- Sanity: right box, right OS ---
if ! grep -q 'VERSION_ID="12"' /etc/os-release 2>/dev/null; then
    echo "❌ This expects Debian 12 (bookworm). /etc/os-release says otherwise."
    echo "   The pinned .deb is built for bookworm's glibc; stopping."
    exit 1
fi

if command -v git >/dev/null 2>&1 && [ -z "${FORCE:-}" ]; then
    say "note: a git is already on PATH at $(command -v git) ($(git --version 2>/dev/null))"
    say "continuing anyway — this installs into ${PREFIX} and does not touch it"
fi

# --- Download + verify ---
mkdir -p "$DLDIR" "$BINDIR"
cd "$DLDIR" || exit 1

if [ -f "$GIT_DEB" ] && [ "$(sha256sum "$GIT_DEB" | cut -d' ' -f1)" = "$GIT_SHA" ]; then
    say "already downloaded and verified: ${GIT_DEB}"
else
    say "downloading ${GIT_DEB} ..."
    if ! curl -sSL --fail -o "$GIT_DEB" "$GIT_URL"; then
        echo "❌ download failed: $GIT_URL"
        exit 1
    fi
    GOT=$(sha256sum "$GIT_DEB" | cut -d' ' -f1)
    if [ "$GOT" != "$GIT_SHA" ]; then
        echo "❌ SHA256 MISMATCH — refusing to install"
        echo "   expected: $GIT_SHA"
        echo "   got     : $GOT"
        rm -f "$GIT_DEB"
        exit 1
    fi
    say "✓ sha256 verified"
fi

# --- Extract (no dpkg database involvement, no root) ---
rm -rf "$PREFIX"
mkdir -p "$PREFIX"
if ! dpkg-deb -x "$GIT_DEB" "$PREFIX"; then
    echo "❌ dpkg-deb extraction failed"
    exit 1
fi
say "✓ extracted to ${PREFIX}"

# --- Wrapper ---
# Debian's git has /usr/lib/git-core compiled in as its exec path, which does
# not exist on this host, so `git fetch` fails with
# "git: 'remote-https' is not a git command". The wrapper points git at its own
# helpers. Paths are baked in (not $HOME) so the wrapper still works under sudo
# or from cron, where HOME differs.
cat > "${BINDIR}/git" <<EOF
#!/bin/sh
# Wrapper for the home-directory git install. Generated by install-git-nas.sh.
# Debian's git hardcodes /usr/lib/git-core as its exec path; that does not exist
# on this appliance, so point git at the unpacked copy instead.
GIT_ROOT="${PREFIX}"
export GIT_EXEC_PATH="\${GIT_ROOT}/usr/lib/git-core"
export GIT_TEMPLATE_DIR="\${GIT_ROOT}/usr/share/git-core/templates"
exec "\${GIT_ROOT}/usr/bin/git" "\$@"
EOF
chmod 755 "${BINDIR}/git"
say "✓ wrapper written to ${BINDIR}/git"

# --- PATH for interactive shells ---
# Placed at the TOP of .bashrc, before Debian's non-interactive early-return
# guard, so `ssh fleetnas git ...` picks it up too.
BLOCK_ID="# >>> native git (install-git-nas.sh) >>>"
if [ -f "${HOME}/.bashrc" ] && grep -qF "$BLOCK_ID" "${HOME}/.bashrc"; then
    say "PATH block already present in ~/.bashrc"
else
    TMP=$(mktemp)
    {
        echo "$BLOCK_ID"
        echo "case \":\$PATH:\" in *\":${BINDIR}:\"*) ;; *) PATH=\"${BINDIR}:\$PATH\" ;; esac"
        echo "export PATH"
        echo "# <<< native git (install-git-nas.sh) <<<"
        echo ""
        [ -f "${HOME}/.bashrc" ] && cat "${HOME}/.bashrc"
    } > "$TMP"
    mv "$TMP" "${HOME}/.bashrc"
    chmod 644 "${HOME}/.bashrc"
    say "✓ PATH block prepended to ~/.bashrc"
fi

# --- Verify ---
echo "=========================================="
echo "   VERIFY                                 "
echo "=========================================="
say "version : $("${BINDIR}/git" --version 2>&1)"
MISSING=$(ldd "${PREFIX}/usr/bin/git" 2>/dev/null | grep -c "not found")
say "missing shared libs: ${MISSING}"
if [ "$MISSING" != "0" ]; then
    echo "❌ unsatisfied libraries — this build does not match the host"
    exit 1
fi
say "helpers : $(ls "${PREFIX}/usr/lib/git-core" 2>/dev/null | wc -l) in git-core"

echo ""
say "Done. Open a new shell (or: export PATH=\"${BINDIR}:\$PATH\") and run:"
say "    git --version"
say "    cd ~/repos/scripts && git status"
echo ""
say "Scripts should call ${BINDIR}/git by absolute path — the wrapper sets its"
say "own environment, so no PATH setup is needed by the caller."
echo ""
