#!/usr/bin/env python3
"""
generate_doc_index.py
Scans the Doc/ folder, extracts first heading or first line for text/markdown files,
and extracts PDF metadata (if PyMuPDF is installed). Produces Doc/_autogen_index.md.

Usage:
  python tools/generate_doc_index.py --doc-dir ./Doc --out ./Doc/_autogen_index.md
"""

import os
import re
import argparse
from pathlib import Path

try:
    import fitz  # PyMuPDF
    have_fitz = True
except Exception:
    have_fitz = False

HEADING_RE = re.compile(r'^\s{0,3}(?:#\s+(.+)|(.+))')

def extract_text_head(path: Path):
    try:
        s = path.read_text(encoding='utf-8', errors='ignore')
    except Exception:
        return None
    # try markdown heading first
    for line in s.splitlines():
        line = line.strip()
        if not line:
            continue
        if line.startswith('#'):
            return line.lstrip('#').strip()
        # short heuristic: first non-empty line (for txt files)
        return line if len(line) < 120 else line[:120] + '...'
    return None

def extract_pdf_meta(path: Path):
    if not have_fitz:
        return {"title": None, "author": None}
    try:
        doc = fitz.open(str(path))
        meta = doc.metadata
        title = meta.get('title') or None
        author = meta.get('author') or None
        doc.close()
        return {"title": title, "author": author}
    except Exception:
        return {"title": None, "author": None}

def main():
    p = argparse.ArgumentParser()
    p.add_argument('--doc-dir', default='Doc', help='directory to scan')
    p.add_argument('--out', default='Doc/_autogen_index.md', help='output markdown file')
    args = p.parse_args()

    docdir = Path(args.doc_dir)
    out = Path(args.out)
    files = sorted([f for f in docdir.iterdir() if f.is_file()])

    lines = []
    lines.append("# Auto-generated Doc Index\n")
    lines.append("Generated by tools/generate_doc_index.py\n")
    lines.append("\n## Files\n")

    for f in files:
        rel = f.relative_to(docdir)
        size_kb = f.stat().st_size / 1024
        ext = f.suffix.lower()
        title = None
        extra = ""
        if ext in {'.md', '.txt', '.html'}:
            title = extract_text_head(f)
        elif ext == '.pdf':
            meta = extract_pdf_meta(f)
            title = meta.get('title') or meta.get('author')
            extra = f" (PDF meta: title={meta.get('title')!r}, author={meta.get('author')!r})"
        else:
            # try to read first line
            title = extract_text_head(f)

        if not title:
            title = "(no heading found)"
        lines.append(f"- [{rel}](./{rel}) — {title} — {size_kb:.1f} KB{extra}")

    out.write_text("\n".join(lines), encoding='utf-8')
    print(f"Wrote {out}")

if __name__ == '__main__':
    main()