# AmsterdamDesktop\Setup-IcloudMailCredential.ps1
# 2026-08-31 UTC -- created
#
# One-time interactive setup: stores the iCloud SMTP app-specific password
# used by Send-FleetMail.ps1 (and everything that dot-sources it, e.g.
# amsdt-health-monitor.ps1 / amsdt-nightly-summary.ps1) for outbound alert
# mail from this box.
#
# The credential is saved via Export-Clixml, which encrypts the password
# with Windows DPAPI keyed to the CURRENT WINDOWS USER ACCOUNT on THIS
# MACHINE. That means:
#   - the resulting file is useless if copied to another machine or read
#     under a different Windows account (by design -- this is why it's
#     fine for this file to live outside the repo's git history)
#   - it must be regenerated by running this script again, once per box,
#     under the same account the scheduled tasks run as
#
# Mirrors the Mac/Ubuntu boxes' ~/.msmtprc (never committed) -- this is
# the Windows equivalent of that file.
#
# Run this manually (not via ssh non-interactive -- Get-Credential needs a
# real console):
#   powershell -NoProfile -ExecutionPolicy Bypass -File Setup-IcloudMailCredential.ps1

$credDir = Join-Path $env:LOCALAPPDATA "fleet-scripts"
$credPath = Join-Path $credDir "icloud-mail-cred.xml"

if (-not (Test-Path $credDir)) {
    New-Item -ItemType Directory -Path $credDir -Force | Out-Null
}

Write-Host "iCloud SMTP credential for fleet health-monitor mail."
Write-Host "Username: the full iCloud email address (e.g. dennis.mathes@icloud.com)"
Write-Host "Password: an APP-SPECIFIC password from appleid.apple.com -- NOT your Apple ID password."
Write-Host ""

$cred = Get-Credential -Message "iCloud SMTP credential (app-specific password)"
$cred | Export-Clixml -Path $credPath

Write-Host ""
Write-Host "Saved (DPAPI-encrypted, this account/machine only) to: $credPath"
Write-Host "Test it with: powershell -NoProfile -File Send-FleetMail.ps1 -Test"
